services:
  db:
    image: postgres:15
    container_name: product_sys_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ../sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ../sql/data.sql:/docker-entrypoint-initdb.d/02_data.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
